name: Run unit tests

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: unit-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests
        run: |
          go test ./...
